import { Barlow } from "next/font/google";
import "./globals.css";
import UperNavigation from "./componants/commmon/navigation/UperNavigation";
import Lowernavigation from "./componants/commmon/navigation/Lowernavigation";
import Footer from "./componants/commmon/footer/Footer";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <div>
          {" "}
          <UperNavigation />
          <Lowernavigation />
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
